/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.2 		*/
/*  Created On : 14-Jul-2022 8:36:15 PM 				*/
/*  DBMS       : SQL Server 2012 						*/
/* ---------------------------------------------------- */

USE master
GO
IF DB_ID('VanMinhBarber') is not NULL
	DROP DATABASE VanMinhBarber
CREATE DATABASE VanMinhBarber
GO
USE VanMinhBarber
GO

/* Drop Foreign Key Constraints */

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_BangGiaSP_SanPham]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [BangGiaSP] DROP CONSTRAINT [FK_BangGiaSP_SanPham]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_BangLuong_NhanVien]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [BangLuong] DROP CONSTRAINT [FK_BangLuong_NhanVien]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_CT_BanHang_HoaDonBanHang]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [CT_BanHang] DROP CONSTRAINT [FK_CT_BanHang_HoaDonBanHang]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_CT_BanHang_SanPham]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [CT_BanHang] DROP CONSTRAINT [FK_CT_BanHang_SanPham]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_CT_DichVu_DichVu]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [CT_DichVu] DROP CONSTRAINT [FK_CT_DichVu_DichVu]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_CT_DichVu_HoaDonDichVu]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [CT_DichVu] DROP CONSTRAINT [FK_CT_DichVu_HoaDonDichVu]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_CT_NhapHang_SanPham]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [CT_NhapHang] DROP CONSTRAINT [FK_CT_NhapHang_SanPham]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_HoaDonNhapHang_DonNhapHang]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [CT_NhapHang] DROP CONSTRAINT [FK_HoaDonNhapHang_DonNhapHang]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_HoaDonBanHang_GiamGia]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [HoaDonBanHang] DROP CONSTRAINT [FK_HoaDonBanHang_GiamGia]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_HoaDonBanHang_KhachHang]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [HoaDonBanHang] DROP CONSTRAINT [FK_HoaDonBanHang_KhachHang]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_HoaDonBanHang_NhanVien]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [HoaDonBanHang] DROP CONSTRAINT [FK_HoaDonBanHang_NhanVien]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_HoaDonDichVu_GiamGia]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [HoaDonDichVu] DROP CONSTRAINT [FK_HoaDonDichVu_GiamGia]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_HoaDonDichVu_KhachHang]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [HoaDonDichVu] DROP CONSTRAINT [FK_HoaDonDichVu_KhachHang]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_HoaDonDichVu_NhanVien]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [HoaDonDichVu] DROP CONSTRAINT [FK_HoaDonDichVu_NhanVien]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_KhachHang_TaiKhoan]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [KhachHang] DROP CONSTRAINT [FK_KhachHang_TaiKhoan]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_NgayLamViec_NhanVien]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [NgayLamViec] DROP CONSTRAINT [FK_NgayLamViec_NhanVien]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_NhanVien_ChiNhanh]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [NhanVien] DROP CONSTRAINT [FK_NhanVien_ChiNhanh]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_NhanVien_TaiKhoan]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [NhanVien] DROP CONSTRAINT [FK_NhanVien_TaiKhoan]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_SanPham_NhaCungCap]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [SanPham] DROP CONSTRAINT [FK_SanPham_NhaCungCap]
GO

/* Drop Tables */

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[BangGiaSP]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [BangGiaSP]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[BangLuong]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [BangLuong]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[ChiNhanh]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [ChiNhanh]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[CT_BanHang]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [CT_BanHang]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[CT_DichVu]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [CT_DichVu]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[CT_NhapHang]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [CT_NhapHang]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[DichVu]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [DichVu]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[GiamGia]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [GiamGia]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[HoaDonBanHang]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [HoaDonBanHang]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[HoaDonDichVu]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [HoaDonDichVu]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[HoaDonNhapHang]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [HoaDonNhapHang]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[KhachHang]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [KhachHang]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[NgayLamViec]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [NgayLamViec]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[NhaCungCap]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [NhaCungCap]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[NhanVien]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [NhanVien]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[SanPham]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [SanPham]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[TaiKhoan]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [TaiKhoan]
GO

/* Create Tables */

CREATE TABLE [BangGiaSP]
(
	[NgayApDung] date NOT NULL,
	[MaSP] char(10) NOT NULL,
	[GiaNhap] float NULL,
	[GiaBan] float NULL
)
GO

CREATE TABLE [BangLuong]
(
	[NgayPhatLuong] date NOT NULL,
	[MaNV] char(10) NOT NULL,
	[Luong] float NULL DEFAULT 0,
	[Thuong] float NULL DEFAULT 0
)
GO

CREATE TABLE [ChiNhanh]
(
	[MaCN] char(10) NOT NULL,
	[TenCN] nvarchar(50) NULL,
	[SoNha] varchar(20) NULL,
	[Duong] nvarchar(30) NULL,
	[Phuong] nvarchar(30) NULL,
	[Quan] nvarchar(30) NULL,
	[TinhThanhPho] nvarchar(30) NULL
)
GO

CREATE TABLE [CT_BanHang]
(
	[STT] int NOT NULL,
	[MaHDBH] char(10) NOT NULL,
	[MaSP] char(10) NULL,
	[SoLuong] int NULL,
	[ThanhTien] float NULL
)
GO

CREATE TABLE [CT_DichVu]
(
	[STT] int NOT NULL,
	[MaDV] char(10) NULL,
	[SoLuong] int NULL,
	[MaHDDV] char(10) NOT NULL,
	[ThanhTien] float NULL
)
GO

CREATE TABLE [CT_NhapHang]
(
	[STT] int NOT NULL,
	[MaHDN] char(10) NOT NULL,
	[MaSP] char(10) NULL,
	[SoLuong] int NULL,
	[ThanhTien] float NULL
)
GO

CREATE TABLE [DichVu]
(
	[MaDV] char(10) NOT NULL,
	[TenDV] nvarchar(50) NULL,
	[LoaiDV] nvarchar(50) NULL,
	[DonGia] float NULL
)
GO

CREATE TABLE [GiamGia]
(
	[MaGiamGia] char(10) NOT NULL,
	[LoaiGiamGia] bit NULL,
	[SoTienGiam] float NULL,
	[PhanTramGiam] float NULL,
	[NgayHetHan] datetime NULL
)
GO

CREATE TABLE [HoaDonBanHang]
(
	[MaHDBH] char(10) NOT NULL,
	[MaKH] char(10) NULL,
	[MaNV] char(10) NULL,
	[NgayLap] datetime NULL,
	[MaGiamGia] char(10) NULL,
	[TongTien] float NULL
)
GO

CREATE TABLE [HoaDonDichVu]
(
	[MaHDDV] char(10) NOT NULL,
	[MaKH] char(10) NULL,
	[NgayLap] datetime NULL,
	[MaGiamGia] char(10) NULL,
	[MaNV] char(10) NULL,
	[TongTien] float NULL
)
GO

CREATE TABLE [HoaDonNhapHang]
(
	[MaHDN] char(10) NOT NULL,
	[NgayNhap] date NULL,
	[TongTien] float NULL
)
GO

CREATE TABLE [KhachHang]
(
	[MaKH] char(10) NOT NULL,
	[TaiKhoan] varchar(50) NULL,
	[HoTen] nvarchar(50) NULL,
	[Email] varchar(50) NULL,
	[SDT] varchar(10) NULL,
	[SoNha] varchar(20) NULL,
	[Duong] nvarchar(30) NULL,
	[Phuong] nvarchar(30) NULL,
	[Quan] nvarchar(30) NULL,
	[TinhThanhPho] nvarchar(30) NULL
)
GO

CREATE TABLE [NgayLamViec]
(
	[NgayLamViec] date NOT NULL,
	[MaNV] char(10) NOT NULL,
	[SoDV] int NULL,
	[CheckIn] time(7) NULL,
	[CheckOut] time(7) NULL
)
GO

CREATE TABLE [NhaCungCap]
(
	[MaNCC] char(10) NOT NULL,
	[TenNCC] nvarchar(50) NULL,
	[DiaChi] nvarchar(100) NULL,
	[SDT] char(10) NULL
)
GO

CREATE TABLE [NhanVien]
(
	[MaNV] char(10) NOT NULL,
	[HoTen] nvarchar(50) NULL,
	[Email] varchar(50) NULL,
	[SDT] char(10) NULL,
	[CMND] char(12) NULL,
	[DiaChi] nvarchar(100) NULL,
	[TaiKhoan] varchar(50) NULL,
	[LoaiNV] nvarchar(50) NULL,
	[ChiNhanh] char(10) NULL
)
GO

CREATE TABLE [SanPham]
(
	[MaSP] char(10) NOT NULL,
	[TenSP] nvarchar(50) NULL,
	[SoLuongTon] int NULL,
	[LoaiSP] nvarchar(50) NULL,
	[NhaCungCap] char(10) NULL
)
GO

CREATE TABLE [TaiKhoan]
(
	[TenTaiKhoan] varchar(50) NOT NULL,
	[MatKhau] varchar(20) NULL,
	[NguoiDung] varchar(50) NULL,
	[VaiTro] varchar(20) NULL,
	[TrangThai] varchar(10) NULL,
	[MaKH] char(10) NULL
)
GO

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE [BangGiaSP] 
 ADD CONSTRAINT [PK_BangGiaSP]
	PRIMARY KEY CLUSTERED ([NgayApDung] ASC,[MaSP] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_BangGiaSP_SanPham] 
 ON [BangGiaSP] ([MaSP] ASC)
GO

ALTER TABLE [BangLuong] 
 ADD CONSTRAINT [PK_BangLuong]
	PRIMARY KEY CLUSTERED ([NgayPhatLuong] ASC,[MaNV] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_BangLuong_NhanVien] 
 ON [BangLuong] ([MaNV] ASC)
GO

ALTER TABLE [ChiNhanh] 
 ADD CONSTRAINT [PK_ChiNhanh]
	PRIMARY KEY CLUSTERED ([MaCN] ASC)
GO

ALTER TABLE [CT_BanHang] 
 ADD CONSTRAINT [PK_CT_BanHang]
	PRIMARY KEY CLUSTERED ([STT] ASC,[MaHDBH] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_CT_BanHang_HoaDonBanHang] 
 ON [CT_BanHang] ([MaHDBH] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_CT_BanHang_SanPham] 
 ON [CT_BanHang] ([MaSP] ASC)
GO

ALTER TABLE [CT_DichVu] 
 ADD CONSTRAINT [PK_CT_DichVu]
	PRIMARY KEY CLUSTERED ([STT] ASC,[MaHDDV] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_CT_DichVu_DichVu] 
 ON [CT_DichVu] ([MaDV] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_CT_DichVu_HoaDonDichVu] 
 ON [CT_DichVu] ([MaHDDV] ASC)
GO

ALTER TABLE [CT_NhapHang] 
 ADD CONSTRAINT [PK_HoaDonNhapHang]
	PRIMARY KEY CLUSTERED ([STT] ASC,[MaHDN] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_CT_NhapHang_SanPham] 
 ON [CT_NhapHang] ([MaSP] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_HoaDonNhapHang_DonNhapHang] 
 ON [CT_NhapHang] ([MaHDN] ASC)
GO

ALTER TABLE [DichVu] 
 ADD CONSTRAINT [PK_DichVu]
	PRIMARY KEY CLUSTERED ([MaDV] ASC)
GO

ALTER TABLE [GiamGia] 
 ADD CONSTRAINT [PK_GiamGia]
	PRIMARY KEY CLUSTERED ([MaGiamGia] ASC)
GO

ALTER TABLE [HoaDonBanHang] 
 ADD CONSTRAINT [PK_HoaDonBanHang]
	PRIMARY KEY CLUSTERED ([MaHDBH] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_HoaDonBanHang_GiamGia] 
 ON [HoaDonBanHang] ([MaGiamGia] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_HoaDonBanHang_KhachHang] 
 ON [HoaDonBanHang] ([MaKH] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_HoaDonBanHang_NhanVien] 
 ON [HoaDonBanHang] ([MaNV] ASC)
GO

ALTER TABLE [HoaDonDichVu] 
 ADD CONSTRAINT [PK_HoaDonDichVu]
	PRIMARY KEY CLUSTERED ([MaHDDV] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_HoaDonDichVu_GiamGia] 
 ON [HoaDonDichVu] ([MaGiamGia] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_HoaDonDichVu_KhachHang] 
 ON [HoaDonDichVu] ([MaKH] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_HoaDonDichVu_NhanVien] 
 ON [HoaDonDichVu] ([MaNV] ASC)
GO

ALTER TABLE [HoaDonNhapHang] 
 ADD CONSTRAINT [PK_DonNhapHang]
	PRIMARY KEY CLUSTERED ([MaHDN] ASC)
GO

ALTER TABLE [KhachHang] 
 ADD CONSTRAINT [PK_KhachHang]
	PRIMARY KEY CLUSTERED ([MaKH] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_KhachHang_TaiKhoan] 
 ON [KhachHang] ([TaiKhoan] ASC)
GO

ALTER TABLE [NgayLamViec] 
 ADD CONSTRAINT [PK_NgayLamViec]
	PRIMARY KEY CLUSTERED ([NgayLamViec] ASC,[MaNV] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_NgayLamViec_NhanVien] 
 ON [NgayLamViec] ([MaNV] ASC)
GO

ALTER TABLE [NhaCungCap] 
 ADD CONSTRAINT [PK_NhaCungCap]
	PRIMARY KEY CLUSTERED ([MaNCC] ASC)
GO

ALTER TABLE [NhanVien] 
 ADD CONSTRAINT [PK_NhanVien]
	PRIMARY KEY CLUSTERED ([MaNV] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_NhanVien_ChiNhanh] 
 ON [NhanVien] ([ChiNhanh] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_NhanVien_TaiKhoan] 
 ON [NhanVien] ([TaiKhoan] ASC)
GO

ALTER TABLE [SanPham] 
 ADD CONSTRAINT [PK_SanPham]
	PRIMARY KEY CLUSTERED ([MaSP] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_SanPham_NhaCungCap] 
 ON [SanPham] ([NhaCungCap] ASC)
GO

ALTER TABLE [TaiKhoan] 
 ADD CONSTRAINT [PK_TaiKhoan]
	PRIMARY KEY CLUSTERED ([TenTaiKhoan] ASC)
GO

/* Create Foreign Key Constraints */

ALTER TABLE [BangGiaSP] ADD CONSTRAINT [FK_BangGiaSP_SanPham]
	FOREIGN KEY ([MaSP]) REFERENCES [SanPham] ([MaSP]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [BangLuong] ADD CONSTRAINT [FK_BangLuong_NhanVien]
	FOREIGN KEY ([MaNV]) REFERENCES [NhanVien] ([MaNV]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [CT_BanHang] ADD CONSTRAINT [FK_CT_BanHang_HoaDonBanHang]
	FOREIGN KEY ([MaHDBH]) REFERENCES [HoaDonBanHang] ([MaHDBH]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [CT_BanHang] ADD CONSTRAINT [FK_CT_BanHang_SanPham]
	FOREIGN KEY ([MaSP]) REFERENCES [SanPham] ([MaSP]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [CT_DichVu] ADD CONSTRAINT [FK_CT_DichVu_DichVu]
	FOREIGN KEY ([MaDV]) REFERENCES [DichVu] ([MaDV]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [CT_DichVu] ADD CONSTRAINT [FK_CT_DichVu_HoaDonDichVu]
	FOREIGN KEY ([MaHDDV]) REFERENCES [HoaDonDichVu] ([MaHDDV]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [CT_NhapHang] ADD CONSTRAINT [FK_CT_NhapHang_SanPham]
	FOREIGN KEY ([MaSP]) REFERENCES [SanPham] ([MaSP]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [CT_NhapHang] ADD CONSTRAINT [FK_HoaDonNhapHang_DonNhapHang]
	FOREIGN KEY ([MaHDN]) REFERENCES [HoaDonNhapHang] ([MaHDN]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [HoaDonBanHang] ADD CONSTRAINT [FK_HoaDonBanHang_GiamGia]
	FOREIGN KEY ([MaGiamGia]) REFERENCES [GiamGia] ([MaGiamGia]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [HoaDonBanHang] ADD CONSTRAINT [FK_HoaDonBanHang_KhachHang]
	FOREIGN KEY ([MaKH]) REFERENCES [KhachHang] ([MaKH]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [HoaDonBanHang] ADD CONSTRAINT [FK_HoaDonBanHang_NhanVien]
	FOREIGN KEY ([MaNV]) REFERENCES [NhanVien] ([MaNV]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [HoaDonDichVu] ADD CONSTRAINT [FK_HoaDonDichVu_GiamGia]
	FOREIGN KEY ([MaGiamGia]) REFERENCES [GiamGia] ([MaGiamGia]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [HoaDonDichVu] ADD CONSTRAINT [FK_HoaDonDichVu_KhachHang]
	FOREIGN KEY ([MaKH]) REFERENCES [KhachHang] ([MaKH]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [HoaDonDichVu] ADD CONSTRAINT [FK_HoaDonDichVu_NhanVien]
	FOREIGN KEY ([MaNV]) REFERENCES [NhanVien] ([MaNV]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [KhachHang] ADD CONSTRAINT [FK_KhachHang_TaiKhoan]
	FOREIGN KEY ([TaiKhoan]) REFERENCES [TaiKhoan] ([TenTaiKhoan]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [NgayLamViec] ADD CONSTRAINT [FK_NgayLamViec_NhanVien]
	FOREIGN KEY ([MaNV]) REFERENCES [NhanVien] ([MaNV]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [NhanVien] ADD CONSTRAINT [FK_NhanVien_ChiNhanh]
	FOREIGN KEY ([ChiNhanh]) REFERENCES [ChiNhanh] ([MaCN]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [NhanVien] ADD CONSTRAINT [FK_NhanVien_TaiKhoan]
	FOREIGN KEY ([TaiKhoan]) REFERENCES [TaiKhoan] ([TenTaiKhoan]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [SanPham] ADD CONSTRAINT [FK_SanPham_NhaCungCap]
	FOREIGN KEY ([NhaCungCap]) REFERENCES [NhaCungCap] ([MaNCC]) ON DELETE No Action ON UPDATE No Action
GO
